### ISSUE TITLE
handling non geocoded locations in database

### ISSUE THREAD

**Issue by Tobias-Horstmann** [OasisLMF/ITWG---AIR-CEDE-to-OED-file#13]
Locations in the cede database that are not properly geocoded seem to stop conversion process.

Error in log file:

2019-11-13 15:30:42,842 INFO Issue in assigning value as per json mapping for ..\augmentations\address_match_mapping.json
2019-11-13 15:30:42,844 ERROR u'NONE'
Traceback (most recent call last):
  File "[]\AIR-CEDE-to-OED-file-master\src\generic_mapping.py", line 104, in value_mapper
    OED_file_direct_mapped.at[index, column_name] = self.json_value_mapper[OED_file_direct_mapped.at[index, column_name]]
KeyError: u'NONE'

**Comment by sbarik5** [comment]
@Tobias-Horstmann , apologies, could not respond earlier. This was taken care in address mapping Json file with a mapping ‘0’ for ‘None’. Couple of CEDEs with geomatchlevel as ‘None’ were tested as well. We will still look into the issue. If you could share your problem CEDE or any other small representative CEDE (without violating compliance issue), we can replicate the problem at our end and fix it..
