### ISSUE TITLE
Pls add server/database name to interactive output

### ISSUE THREAD

**Issue by jeremyzechar** [OasisLMF/ITWG---AIR-CEDE-to-OED-file#2]
It's great to have some status update as the CEDE to OED conversion is progressing, but I think it'd be helpful if the very first line confirmed the server and database that is being converted. Rather than

> Process started!

I'd find it useful to have a msg like

> Starting to convert CEDE _AirExp_xxxx_ on _servername_ to OED file!

**Comment by sbarik5** [comment]
Sure, will incorporate this

**Comment by shivamspj** [comment]
Hi **@jeremyzechar,**
We have implemented this enhancement for **develop-cr** branch. 
Thanks
