### ISSUE TITLE
Should `query_tlclx_tlc` use left joins?

### ISSUE THREAD

**Issue by paulroden** [OasisLMF/ITWG---AIR-CEDE-to-OED-file#7]
https://github.com/shivamspj/AIR-CEDE-to-OED-file/blob/870889f57076808410e1ce196715bcdc3c7074a1/augmentations/config.ini#L3

tLocTerm should be `left join`ed to `tLayerConditionLocationXref` so as to allow for locations which do not have layer conditions. It's not clear what's best done with the second join as the syntax is somewhat vague, so I suggest cleaning this up so the intention is clearer when read.

**Comment by Tobias-Horstmann** [comment]
Dear all, entered the same problem as it seems that the left join didn't make it in the master branch yet?
